//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LucasAlias.NINA.NinaPP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NINA_Image_ImageAnalysis_BayerFilter16bpp {
            get {
                return ((bool)(this["NINA_Image_ImageAnalysis_BayerFilter16bpp"]));
            }
            set {
                this["NINA_Image_ImageAnalysis_BayerFilter16bpp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NINA_Image_ImageAnalysis_ColorRemappingGeneral {
            get {
                return ((bool)(this["NINA_Image_ImageAnalysis_ColorRemappingGeneral"]));
            }
            set {
                this["NINA_Image_ImageAnalysis_ColorRemappingGeneral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NINA_Image_ImageAnalysis_FastGaussianBlur {
            get {
                return ((bool)(this["NINA_Image_ImageAnalysis_FastGaussianBlur"]));
            }
            set {
                this["NINA_Image_ImageAnalysis_FastGaussianBlur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NINA_Image_ImageAnalysis_StarDetection {
            get {
                return ((bool)(this["NINA_Image_ImageAnalysis_StarDetection"]));
            }
            set {
                this["NINA_Image_ImageAnalysis_StarDetection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Accord_Imaging_BlobCounter {
            get {
                return ((bool)(this["Accord_Imaging_BlobCounter"]));
            }
            set {
                this["Accord_Imaging_BlobCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Accord_Imaging_BlobCounterBase {
            get {
                return ((bool)(this["Accord_Imaging_BlobCounterBase"]));
            }
            set {
                this["Accord_Imaging_BlobCounterBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Accord_Imaging_Filters_BinaryDilation3x3 {
            get {
                return ((bool)(this["Accord_Imaging_Filters_BinaryDilation3x3"]));
            }
            set {
                this["Accord_Imaging_Filters_BinaryDilation3x3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Accord_Imaging_Filters_CannyEdgeDetector {
            get {
                return ((bool)(this["Accord_Imaging_Filters_CannyEdgeDetector"]));
            }
            set {
                this["Accord_Imaging_Filters_CannyEdgeDetector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Accord_Imaging_Filters_Convolution {
            get {
                return ((bool)(this["Accord_Imaging_Filters_Convolution"]));
            }
            set {
                this["Accord_Imaging_Filters_Convolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Accord_Imaging_Filters_NoBlurCannyEdgeDetector {
            get {
                return ((bool)(this["Accord_Imaging_Filters_NoBlurCannyEdgeDetector"]));
            }
            set {
                this["Accord_Imaging_Filters_NoBlurCannyEdgeDetector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Accord_Imaging_Filters_ResizeBicubic {
            get {
                return ((bool)(this["Accord_Imaging_Filters_ResizeBicubic"]));
            }
            set {
                this["Accord_Imaging_Filters_ResizeBicubic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Accord_Imaging_Filters_SISThreshold {
            get {
                return ((bool)(this["Accord_Imaging_Filters_SISThreshold"]));
            }
            set {
                this["Accord_Imaging_Filters_SISThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NINA_Image_ImageAnalysis_BayerFilter16bpp__MT {
            get {
                return ((bool)(this["NINA_Image_ImageAnalysis_BayerFilter16bpp__MT"]));
            }
            set {
                this["NINA_Image_ImageAnalysis_BayerFilter16bpp__MT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Accord_Imaging_Filters_ResizeBicubic__MT {
            get {
                return ((bool)(this["Accord_Imaging_Filters_ResizeBicubic__MT"]));
            }
            set {
                this["Accord_Imaging_Filters_ResizeBicubic__MT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Accord_Imaging_Filters_Convolution__MT {
            get {
                return ((bool)(this["Accord_Imaging_Filters_Convolution__MT"]));
            }
            set {
                this["Accord_Imaging_Filters_Convolution__MT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NINA_Image_ImageAnalysis_BayerFilter16bpp__OpCL {
            get {
                return ((string)(this["NINA_Image_ImageAnalysis_BayerFilter16bpp__OpCL"]));
            }
            set {
                this["NINA_Image_ImageAnalysis_BayerFilter16bpp__OpCL"] = value;
            }
        }
    }
}
